import { Property } from "./types";

export const properties: Property[] = [
  {
    id: "obsidian-heights-villa",
    title: "The Obsidian Heights Villa",
    location: "Nyarutarama, Kigali",
    price: "$2,450,000",
    description: "An ultra-modern luxury villa with floor-to-ceiling glass walls and a private infinity pool overlooking lush Rwandan hills.",
    type: "house",
    offer: "buy",
    beds: 6,
    baths: 5.5,
    area: "850 sqm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDgEf8FYc-JtRPthjt9JubutE_yuOoNMK1U-rfDzukAX6mxvX1BVLMaa1wxwMkEFo5Vwsad_CQ8WYi6wXY2kbkhzNcIFrYSeen0bI6vQBZ-DoEvcEYihNhzZoMeV6X4Wxw0dSBCZ7ffb44-GvvBbZuBVAN1_pR2YwnNANrf36PRs28KOHgjuKZis2nu0koh9sDe1sEDgxiFXxUWpOLutTaN4XnCsrKUbGvyuvyEOdXjSkaUjKEuFPL25TJP_9btNPp5fbuqqUi5WF0",
    features: ["Infinity Pool", "Private Cinema", "Wine Cellar", "City View"],
    status: "active",
  },
  {
    id: "skyline-plateau",
    title: "The Skyline Plateau",
    location: "Rebero Hill",
    price: "$680,000",
    description: "Vast green hilltop landscape in Rebero with a panoramic view of Kigali city skyline under a soft twilight sky.",
    type: "land",
    offer: "buy",
    area: "2.5 Hectares",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuA6vXFpye6QsnkR2eA-n7qcUQ2xIZEja7eH3pQYSPVcbDEkG_BpwHQthAjvo4ekKfP-sWp9jRN83sXDKA2cW19EacDK-Fp-CrnENU8jfr5GGSmcktuwjeBDjjibbeI5G4_Hanq0favs3ttybu2jgZk21r-BU_DNIP7E11IBkB_KYBpn9DoeWRRETCG1wfj_ySnkIqsDpkY7xwcUt0DbHY55Y9E05S0c4OhFP5Zh1IreENO7zMgsDKBBh5s-c-gsqTh5dctBE6gSY04",
    features: ["Panoramic View", "Development Ready", "Secure Title"],
    status: "active",
  },
  {
    id: "zen-garden-estate",
    title: "The Zen Garden Estate",
    location: "Kibagabaga, Kigali",
    price: "$12,000/mo",
    description: "Modern brutalist style house with dark wood accents and large balconies surrounded by tropical gardens.",
    type: "house",
    offer: "rent",
    beds: 4,
    baths: 4,
    area: "450 sqm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCFJLwyhhnp-ej_o8EfOyvhIUqlkSbtmPuAfMFjNTqZzx_4tutaiCAqv88bdlL6p3d8nc8iZsnLIWxK2NkY4g4fp2ayfZ5PM467GkiLpswpFDAoP5TX5PrtaHUG3L_E4aZrYg8hxaD6SzVV2J6Bw8VM2UzHbUFYRGtkMV2cdjGj7N6TyDAqkb8ccebpNNHKZKN1nl0q2MoQNNmj8gdnUx-2Uvqr70Ii64YUUT_R2gES8VldgRE4D2HyAlHFTFluQIM6PwpuRvXZLKs",
    features: ["Infinity Pool", "Gated Community", "Tropical Garden"],
    status: "active",
  },
  {
    id: "kivu-emerald-estate",
    title: "The Kivu Emerald Estate",
    location: "Gisenyi, Lake Kivu",
    price: "$1,890,000",
    description: "Luxury eco-retreat bungalow on the edge of Lake Kivu with natural stone walls and a wide wooden deck over the water.",
    type: "house",
    offer: "buy",
    beds: 4,
    baths: 4,
    area: "420 sqm",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuB8xWUDEHZiDW7d23GieVNdyrYU0XPioOJ80z6KMVCDtuWFB2ygJxGeQ7tOlIY24TYDGld81GrxxdmSjIvPmDoM_G4R1k09rwrAPBLL7WQje812-Rwd8cN3rqVGrTVehsF1NjsynJoJq-bjymePC88Z9nDE9ApSSjRIBrioOSqBja3_TOrkXuoGbeaixLBSfm4pU9M2rnR7sA8Tkk_GT6vAfQhXRmfEIRutIftFd2bd-q61c85lAJfqsDnXClfQgjkxO9VBENfWquc",
    features: ["Lakefront", "Private Spa", "Organic Architecture", "Private Dock"],
    status: "active",
  }
];
